--- 
name: "Building DNS"
true: 
    pull_request: 
        branches: 
            - main
    push: 
        branches: 
            - main

on: push

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - 
                uses: actions/checkout@v2
            - 
                name: "Use Node.js"
                uses: actions/setup-node@v1
                with: 
                    node-version: 12.x
            - 
                name: "Install dependencies"
                run: "npm install"
            - 
                run: "npm run build"
